package com.example.restaurantmanagementsystem.dto.request;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class BillRequestDTO {
    @NotNull(message = "Branch Id is required")
    private Long branchId;

    @NotNull(message = "Order Id is required")
    private Long orderId;

    @NotNull(message = "Generated By Id is required")
    private Long generatedById;

    @DecimalMax(value = "25.00", message = "Discount cannot exceed 25%")
    @DecimalMin(value = "0.00", message = "Discount cannot be negative")
    private BigDecimal discountPercentage = BigDecimal.ZERO;

}
